### PR TITLE
Added possibility to hide menu by pressing escape key

### PR DESCRIPTION
**Pull request by jbiron**
After a lot of mistakes, i think i finally got it...

### CODE REVIEW

**Comment by jbiron** [comment]
oh damn!

**Comment by oldergod** [comment]
Why do you create a new PR each time? Couldn't you just fix it?

**Comment by jbiron** [comment]
Well i tried but i thought revert commit would acutually revert commit but since it push the old version on top it seems i can't resolve this but burn my fork and start a new one unless i missed something. Could be since it's my first pr, any help is welcome here

**Comment by oldergod** [comment]
I think you need to [sync your forked repo](https://help.github.com/articles/syncing-a-fork/), then rebase, then push again.

**Pull request closed without merging**
