### PR TITLE
_frameTime in ms

### LINKED ISSUE #89: animated-clip: creating the stylesheet with keyframes takes too long
The generation of the stylesheet for the keyframes takes almost 200ms
screen shot 2017-05-31 at 6 22 44 pm

I tried saving the contents into a separate file, but it is ~3MB non-gzipped!
This could probably be reduced to half by using [animation-direction](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-direction).

### PR DESCRIPTION
**Pull request by valdrinkoshi**
Fixes #89

### CODE REVIEW

**Comment by surma** [comment]
Good catch. Thanks

**Review by surma — CHANGES_REQUESTED** [review]
I don't think you can reverse as the animation curve might not be symmetrical. Can you add those sections back in? 

The frame rate fix is important and correct tho!

**Comment by valdrinkoshi** [comment]
@surma good point, done 👌

**Comment by surma** [comment]
A+! Thanks @valdrinkoshi

**Review by surma — APPROVED** [review]

**Pull request merged**
