### PR TITLE
Moved document eventlistener to sideNav

### PR DESCRIPTION
**Pull request by DanielVoogsgerd**
Let me start by thanking you for the awesome walkthroughs. They are both enjoyable to watch and very educational.

I noticed that you bind the eventlistener to the document instead of the `sideNav__container`; I prefer the behaviour aswell, but I think binding to the `sideNav` is even more appropriate. This way everything is much nicer contained to just the elements inside `sideNav`.

### CODE REVIEW

**Comment by DanielVoogsgerd** [comment]
I signed it!

**Comment by TWiStErRob** [comment]
+1 I was thinking about this too while watching, since that element is 100% anyway.

**Comment by DanielVoogsgerd** [comment]
Did I miss something?

**Comment by paullewis** [comment]
Woah! No you didn't. Looks like me switching to gh-pages only (no master) closed the PR. Eesh. Sorry. Can you PR it in again?

**Comment by DanielVoogsgerd** [comment]
Haha, that's odd. Here you go.

**Pull request closed without merging**
