### PR TITLE
Removed need for two functions to display the menu

### PR DESCRIPTION
**Pull request by alexnewmannn**
-   Add a toggle funtion
-   Remove unnecessary paramters
-   Remove need for dom lookup to check menu state
-   Fixed some jshint issues
-       Make touchEnd only fire when necessary
-   Fix issue where overlay intermittently disappears early #13

### CODE REVIEW

**Comment by paullewis** [comment]
I like where it's headed, but I disagree over the `toggleSideNav` function; I prefer that we'd keep it separate, because I prefer the idea that each function just does a single thing. Also, I _think_ that `classList.toggle` doesn't work in IE, which, granted is superseded by Edge, but I wonder if it's just a touch too soon to drop this.

**Comment by alexnewmannn** [comment]
Yeh I was in two minds about that, I do like the idea of explicitly telling it to close, and explicitly telling to open but i also don't like a lot of code repetition. I can revert that, sure. Other than that, any other suggestions? If not, ill remove the toggle and commit.
Also, for future notice toggle is IE10+, however, the second parameter (force) is Edge plus I believe :)

**Comment by TWiStErRob** [comment]
@paullewis I think using flex also kind-of excludes IE, according to [caniuse](http://caniuse.com/#search=Flex).
On YT Live it would be intesting to spend a few minutes at the end of the videos firing up some other browsers to see how/if it works.

**Comment by paullewis** [comment]
This got autoclosed because I removed the master branch. Can you PR it in again?

**Comment by alexnewmannn** [comment]
sure will do it today.

**Pull request closed without merging**
